<a href="https://colab.research.google.com/github/afrenkai/CUDA-MATMUL-WORKSHOP/blob/main/CUPYMATMUL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import cupy as cpy

# Matrix size (N x N)
N = 1024

# Create random matrices A and B
A = cpy.random.rand(N, N).astype(cpy.float32)
B = cpy.random.rand(N, N).astype(cpy.float32)

# Allocate memory for the result matrix C

# zeros literally makes a zero matrix [[0,0], [0,0]] of size NxN (the example here is N = 2)

C = cpy.zeros((N, N), dtype=cpy.float32)

# Perform matrix multiplication using CuPy (this is done on GPU)
C = cpy.matmul(A, B)

# Copy the result back to the host (if needed, but unnecessary for GPU-only operations)
C_host = cpy.asnumpy(C)

# Print a portion of the result
print(C_host)


[[255.94768 253.20157 255.33084 ... 257.97128 253.96402 263.30676]
 [254.0603  251.29208 256.33606 ... 257.70004 253.79645 259.91302]
 [259.87488 256.10492 263.8799  ... 269.3301  262.39664 267.78268]
 ...
 [256.88297 249.0023  255.15099 ... 261.4211  251.97107 258.4483 ]
 [253.96637 247.39651 252.47224 ... 254.45552 253.09186 257.19742]
 [260.76877 251.97546 261.6092  ... 265.2931  253.9288  258.9859 ]]


In [ ]:
!pip install